- name: CoreDNS Helm Overrides
  become: true
  template:
    src: k8s-coredns-overrides-yaml.j2
    dest: "{{ k8s_coredns_helm_overrides }}"
    backup: true

- name: add helm repository to user
  become: true
  become_user: '{{ user }}'
  shell: "helm repo add coredns https://coredns.github.io/helm"
  args:
    executable: /bin/bash

- name: update helm repos
  become: true
  become_user: '{{ user }}'
  shell: "helm repo update coredns"
  args:
    executable: /bin/bash
  changed_when: true

- name: Deploy CoreDNS helm chart
  kubernetes.core.helm:
    name: coredns
    chart_ref: coredns/coredns
    chart_version: 1.29.0
    release_namespace: coredns
    values_files:
      - "{{ k8s_coredns_helm_overrides }}"
