# code: language=ansible
---
- name: Docker
  ansible.builtin.include_tasks: docker.yml
- name: Cuda Toolkit
  ansible.builtin.include_tasks: cuda-toolkit.yml
- name: Nvidia Container Toolkit
  ansible.builtin.include_tasks: nvidia-container-toolkit.yml
- name: Kubernetes
  ansible.builtin.include_tasks: kubernetes.yml
- name: Helm
  ansible.builtin.include_tasks: helm.yml
- name: MicroK8S
  ansible.builtin.include_tasks: microk8s.yml
