- name: microk8s | configure microk8s options
  become: true
  template:
    src: etc-microk8s-yaml.j2
    dest: /etc/microk8s.yaml
    backup: true
    mode: 0644

- name: Install microk8s
  become: true
  snap:
    name: microk8s
    state: present
    classic: true
    channel: "{{ microk8s_channel }}"

- name: Wait for microk8s to be ready
  become: true
  command: |
    microk8s status --wait-ready
  changed_when: false
  register: mk8sstatusout
  failed_when:
      - mk8sstatusout.rc > 0

- name: microk8s | group members
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  with_items: 
    - "{{ user }}"

- name: create kube directory
  become_user: "{{ user }}"
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ helm_download_dir }}'

- name: Create .kube folder for the user
  become: true
  become_user: '{{ user }}'
  file:
    path: "/home/{{ user }}/.kube"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0750

- name: create kubectl config
  become: true
  changed_when: true
  shell: microk8s config > /home/{{ user }}/.kube/config
  args:
    executable: /bin/bash

- name: reaffirm permission on files
  become: true
  file:
    path: "/home/{{ user }}/.kube"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    recurse: yes
    mode: 0750
