# code: language=ansible
---
- name: Cert Manager Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: cert-manager-overrides-yml.j2
    dest: "{{ cert_manager_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'

- name: Add Cert Manager chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: cert-manager
    repo_url: "https://charts.jetstack.io"

- name: Deploy Cert Manager helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: cert-manager
    release_namespace: cert-manager
    chart_ref: cert-manager/cert-manager
    chart_version: v1.13.3
    create_namespace: true
    update_repo_cache: true
    wait: true
    values_files:
      - "{{ cert_manager_helm_overrides }}"
