# code: language=ansible
---
- name: Cilium Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: cilium-overrides-yml.j2
    dest: "{{ cilium_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: cilium_helm_overrides_result

- name: Add Cilium chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"

- name: Deploy Cilium helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: cilium
    release_namespace: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_helm_version }}"
    create_namespace: true
    update_repo_cache: cilium_helm_overrides_result.changed | default(true)
    wait: true
    values_files:
      - "{{ cilium_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (cilium_helm_overrides_result.changed | default(true))
