# code: language=ansible
---
- name: Generate a password
  ansible.builtin.set_fact:
    etcd_root_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

- name: Etcd cert-manager crds Yaml
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: etcd-cert-manager-crds-yml.j2
    dest: "{{ etcd_cert_manager_crds_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Deploy Etcd cert-manager crds
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    namespace: etcd
    state: present
    src: "{{ etcd_cert_manager_crds_yml }}"
    wait: yes

- name: ETCD Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: etcd-overrides-yml.j2
    dest: "{{ etcd_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'

- name: Deploy ETCD helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: etcd
    release_namespace: etcd
    chart_ref: oci://registry-1.docker.io/bitnamicharts/etcd
    chart_version: "{{ etcd_helm_version }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    values_files:
      - "{{ etcd_helm_overrides }}"
