# code: language=ansible
---
- name: External Secrets Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: external-secrets-overrides-yml.j2
    dest: "{{ external_secrets_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'

- name: Add External Secrets chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: coredns
    repo_url: "https://coredns.github.io/helm"

- name: Deploy External Secrets helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: coredns
    release_namespace: coredns
    chart_ref: coredns/coredns
    chart_version: "{{ external_secrets_helm_version }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    values_files:
      - "{{ external_secrets_helm_overrides }}"
