# code: language=ansible
---
- name: Kube-Prometheus-Stack Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: kube-prometheus-stack-overrides-yml.j2
    dest: "{{ kube_prometheus_stack_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'

- name: Add Kube-Prometheus-Stack chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: kube-prometheus-stack
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy Kube-Prometheus-Stack helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: kube-prometheus-stack
    release_namespace: kube-prometheus-stack
    chart_ref: kube-prometheus-stack/kube-prometheus-stack
    chart_version: 61.7.2
    create_namespace: true
    update_repo_cache: true
    wait: true
    values_files:
      - "{{ kube_prometheus_stack_helm_overrides }}"
