# code: language=ansible
---
# - name: Cilium
#   ansible.builtin.include_tasks: cilium.yml
# - name: Hostpath Provisioner
#   ansible.builtin.include_tasks: hostpath-provisioner.yml
- name: Core DNS
  ansible.builtin.include_tasks: coredns.yml
- name: K8S Gateway
  ansible.builtin.include_tasks: k8s-gateway.yml
- name: NFS CSI
  ansible.builtin.include_tasks: nfs-csi.yml
- name: SMB CSI
  ansible.builtin.include_tasks: smb-csi.yml
- name: Traefik
  ansible.builtin.include_tasks: traefik.yml
# - name: ApiSix
#   ansible.builtin.include_tasks: apisix.yml
- name: Cert Manager
  ansible.builtin.include_tasks: cert-manager.yml
- name: WhoAmI
  ansible.builtin.include_tasks: whoami.yml
- name: Postgres Operator
  ansible.builtin.include_tasks: postgres-operator.yml
- name: Postgres Operator UI
  ansible.builtin.include_tasks: postgres-operator-ui.yml
- name: Postgres Cluster
  ansible.builtin.include_tasks: postgres-cluster.yml
- name: Redis Operator
  ansible.builtin.include_tasks: redis-operator.yml
- name: OpenSearch Operator
  ansible.builtin.include_tasks: opensearch-operator.yml
- name: Ollama
  ansible.builtin.include_tasks: ollama.yml
- name: Open WebUI
  ansible.builtin.include_tasks: open-webui.yml
- name: Flowise
  ansible.builtin.include_tasks: flowise.yml

- name: Manual host setup instructions
  ansible.builtin.include_tasks: manual-host-setup.yml
