# code: language=ansible
---
- name: Hostpath Provisioner
  ansible.builtin.include_tasks: hostpath-provisioner.yml
- name: Core DNS
  ansible.builtin.include_tasks: coredns.yml
- name: K8S Gateway
  ansible.builtin.include_tasks: k8s-gateway.yml
- name: NFS CSI
  ansible.builtin.include_tasks: nfs-csi.yml
- name: SMB CSI
  ansible.builtin.include_tasks: smb-csi.yml
- name: Traefik
  ansible.builtin.include_tasks: traefik.yml
- name: Cert Manager
  ansible.builtin.include_tasks: cert-manager.yml
