# code: language=ansible
---
- name: Trust Manager Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: trust-manager-overrides-yml.j2
    dest: "{{ trust_manager_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'

- name: Add Trust Manager chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: trust-manager
    repo_url: "https://charts.jetstack.io"

- name: Deploy Trust Manager helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: trust-manager
    release_namespace: trust-manager
    chart_ref: cert-manager/trust-manager
    chart_version: v0.9.0
    create_namespace: true
    update_repo_cache: true
    wait: true
    values_files:
      - "{{ trust_manager_helm_overrides }}"

- name: trust-manager crds Yaml
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: trust-manager-overrides-yml.j2
    dest: "{{ trust_manager_crds_yml }}"
    mode: 'u=rw,g=r,o=r'

# - name: Deploy trust-manager crds
#   become: true
#   become_user: '{{ user }}'
#   kubernetes.core.k8s:
#     namespace: cert-manager
#     state: present
#     src: "{{ trust_manager_crds_yml }}"
#     wait: yes
